### ISSUE TITLE
Affirm authorization with no Solidus order

### ISSUE THREAD

**Issue by seandawes** [solidusio/solidus_affirm#33]
We had a customer reach out about an order he had placed that he had not received any follow-up information on. Normally this is because the customer completed the Affirm portion of the checkout but not the confirmation page when redirected back to the site, but this will result in an incomplete order if you search including incomplete orders in a search in the order admin. Which this is a [separate issue](https://github.com/solidusio-contrib/solidus_affirm/issues/32) with the affirm implementation

This one is strange because there is no order in our backend that we can find. Checked using his name, the order ID assigned in Affirm and his email address. Also checked using the SKU of one of the line items listed in Affirm. Did find an incomplete order for the email address, but the line items that were in the cart did not match, and there were no payment attempts in that order.

Have examples of this on our store with customer info and records but cannot publicly list this.

**Comment by peterberkenbosch** [comment]
This needs some more research around cleaning and merging "abandon carts", however I think if we have #32 implemented (i.e. making affirm part of the complete step) it will prevent these things from happing.

**Comment by kennyadsl** [comment]
I think we can close this one now, thanks @AlistairNorman!

**Comment by peterberkenbosch** [comment]
Yes!
