### ISSUE TITLE
Handle back button from :confirm state

### ISSUE THREAD

**Issue by peterberkenbosch** [solidusio/solidus_affirm#54]
In the confirm state the user uses the back button the select the affirm payment and moves next. This is breaking the AASM. 

This one is related to #32 as well, when the Affirm Payment completion is part of the confirm / completion of the order this will also be not a problem with the state machine.

**Comment by peterberkenbosch** [comment]
back buttons are a challenge, we need to add some more fallbacks before redirecting to Affirm after an user uses the back button from Confirm to Payment step.

**Comment by kennyadsl** [comment]
I think we can close this one now, thanks @AlistairNorman!

**Comment by peterberkenbosch** [comment]
Yes indeed! Thanks! Closing
